import { prisma } from "./db";

const specialists = prisma.specialists.createMany({
  data: [
    {
      imagePath: "@/assets/doctors/1.png",
      name: "Хагай Елена Игоревна",
      role: "Детский Кардиолог",
      description: "Директор клиники, MD, MSc, MBA",
      experience: 12,
      qualification: "Врач первой категории",
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor20.png",
      name: "Райханов Мурат Арыстанович",
      role: "Кардиохирург",
      description: "Главный внештатный кардиохирург Павлодарской Области",
      experience: 12,
      qualification: "Врач высшей категории",
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor19.png",
      name: "Муканова Гульнара Халеловна",
      role: "Врач каридолог",
      description: "Главный внештатный кардиолог г. Павлодар",
      experience: 12,
      qualification: "Врач высшей категории",
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor18.png",
      name: "Сарсекеева Асем Шакеровна",
      role: "Детский кардиолог",
      description: "Something",
      experience: 12,
      qualification: "Врач первой категории",
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor17.png",
      name: "Сабеков Ринат Дулатбекович",
      role: "Сосудистый хирург, флеболог, рентгенохирург",
      description: "MD, MSc",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor16.png",
      name: "Смаилов Совет Сляммуратович",
      role: "Детский Хирург",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor15.png",
      name: "Жусупов Сабит Муталяпович",
      role: "Сосудистый хирург, флеболог",
      description: "Кандидат медицинских наук",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor13.png",
      name: "Темирбулатов Ринат Хамзаевич",
      role: "Специалист Ультразвуковой Диагностики",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor12.png",
      name: "Муратов Даниил Ринатович",
      role: "Врач уролог-андролог",
      description: "MD",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor12.png",
      name: "Тулебаев Мусаип Мусаевич",
      role: "Детский травмотолог-ортопед",
      description: "Something",
      qualification: "Врач первой категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor10.png",
      name: "Онбаева Асель Руслановна",
      role: "Врач-педиатр, MD",
      description: "Something",
      qualification: "Врач скорой неотложной помощи",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor9.png",
      name: "Талгат Асылбек Талгатулы",
      role: "Детский инфекционист, гепатолог, паразитолог",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor8.png",
      name: "Асылханов Нуржан Канатович",
      role: "Сосудистый Хирург, флеболог, Врач Ультразвуковой Диагностики",
      description: "MD, MSc",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor7.png",
      name: "Рафиков Фарух Фаридович",
      role: "Взрослый, детский невролог",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor6.png",
      name: "Могер Наталья Борисовна",
      role: "Врач педиатр",
      description: "Something",
      qualification: "Первая квалификационная категория",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "",
      name: "Шайкенов Алмас Мерекулы",
      role: "Кардиохирург, Врач ультразвуковой диагностики",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "@/assets/doctors/doctor3.png",
      name: "Темиргалиев Галымжан Абаевич",
      role: "Врач онколог-маммолог",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "",
      name: "Наукенова Бахыт Кастаевна",
      role: "Взрослый Кардиолог",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "",
      name: "Иманов Арман Казиретович",
      role: "Детский Невролог",
      description: "Главный внештатный детский невролог Павлодарской области",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
    {
      imagePath: "",
      name: "Тулеугазинова Айгерим Еркынова",
      role: "Аллерголог",
      description: "Something",
      qualification: "Врач высшей категории",
      experience: 12,
      workingSince: 2020,
    },
  ],
});

const services = prisma.services.createMany({
  data: [
    {
      name: "Ортопед-травмотолог",
      type: "CONSULTATION",
      description:
        "Детский ортопед-травматолог специализируется на диагностике, лечении и профилактике заболеваний опорно-двигательного аппарата у детей от рождения до 18 лет. Врач занимается лечением врожденных и приобретенных деформаций костей, суставов, мышц и связок, травм различной степени тяжести, нарушений осанки и походки. Особое внимание уделяется раннему выявлению патологий развития, таких как дисплазия тазобедренных суставов, плоскостопие, сколиоз, косолапость. Консультации включают комплексный осмотр, функциональные тесты, при необходимости назначение дополнительных исследований. Врач разрабатывает индивидуальные программы лечения, включающие консервативные методы, лечебную физкультуру, физиотерапию, а также дает рекомендации по профилактике заболеваний опорно-двигательной системы.",
    },
  ],
});
